services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ZIG_BUILD_TARGET: aarch64-linux-gnu # modify this if not building on raspi/macos
    image: iridoporth-backend:dev
    environment:
      IRIDOPORTH_PORT: 3000
      IRIDOPORTH_DB_PATH: /var/lib/iridoporth/iridoporth.db
    expose:
      - "3000"
    volumes:
      - iridoporth-db:/var/lib/iridoporth
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: alpine:3.19
    container_name: iridoporth-db
    command: [ "sh", "-c", "mkdir -p /var/lib/iridoporth && touch /var/lib/iridoporth/iridoporth.db && chmod 666 /var/lib/iridoporth/iridoporth.db && sleep infinity" ]
    volumes:
      - iridoporth-db:/var/lib/iridoporth
    restart: unless-stopped

  frontend:
    build:
      context: ../Iridoporth-frontend
      dockerfile: Dockerfile
    image: iridoporth-frontend:dev
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  iridoporth-db:
